server:
  port: 8086
  forward-headers-strategy: framework

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://mysql:3306/auth_db
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092
    template:
      observation-enabled: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

springdoc:
  api-docs:
    path: /microbank/auth/v3/api-docs
  swagger-ui:
    path: /microbank/auth/swagger-ui.html
  override-with-generic-response: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3, w3c
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name},traceId=%X{traceId},spanId=%X{spanId}]"

jwt:
  secret: ${JWT_SECRET_KEY}