server:
  port: 8085
  forward-headers-strategy: framework

spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:mysql://mysql:3306/transaction_db
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: kafka:9092
    listener:
      observation-enabled: true
    consumer:
      group-id: transaction-service
      auto-offset-reset: earliest

springdoc:
  api-docs:
    path: /microbank/transactions/v3/api-docs
  swagger-ui:
    path: /microbank/transactions/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info

  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3, w3c

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

jwt:
  secret: "${JWT_SECRET_KEY}"

logging:
  level:
    org.springframework.kafka: INFO
  pattern:
    level: "%5p [${spring.application.name},traceId=%X{traceId},spanId=%X{spanId}]"